### ISSUE TITLE
Display quoted tweets

### ISSUE THREAD

**Issue by AverageMarcus** [klinker24/talon-twitter-holo#13]
With Twitters new quoted retweets Talon just displays the link to the original tweet. It would be good if this could be displayed in a similar manner to the Twitter website.

**Comment by klinker24** [comment]
I don't see this ever happening on the timeline. There would be to many conflicts with the theme engine. I probably will put something on the tweet viewer in the future though.

**Comment by AverageMarcus** [comment]
The conversation page seems suitable to me.

**Comment by klinker24** [comment]
This is done with the new version of Talon: https://github.com/klinker24/talon-twitter-material
