### ISSUE TITLE
Deprecation of legacy Direct Message Endpoints in June 2018

### ISSUE THREAD

**Issue by sleeksorrow** [klinker24/talon-twitter-holo#42]
Hello there!

This is just for your information, that legacy Direct Message endpoints will be shut off in June 2018, in case I didn't read that wrong:
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734

Thank you for your great work!

**Comment by klinker24** [comment]
Yeah, I saw. That sucks. I won't be able to do anything about this until Twitter4j includes the new APIs or I build them in.

The `UserStream` is also deprecated. Which will be a bigger change.

**Comment by klinker24** [comment]
This will be closed in favor of https://github.com/klinker24/talon-twitter-material/issues/34
